server: "hub-cloud.browserstack.com"
user: <%= ENV['BROWSERSTACK_USERNAME'] %>
key: <%= ENV['BROWSERSTACK_ACCESS_KEY'] %>

common_caps:
  "build": "capybara-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"